eric-ingressgw-nrf-agent-traffic:
  service:
    allocateLoadBalancerNodePorts: true
  labels:
    istiox: eric-nrf-agent-traffic
  enabled: true
  daemonSet: false
  ports:
  - name: http2
    port: 85
    targetPort: 8085

eric-ingressgw-nrf-provisioning:
  service:
    allocateLoadBalancerNodePorts: true
  labels:
    istiox: eric-nrf-provisioning
  enabled: true
  daemonSet: false
  ports:
  - port: 80
    targetPort: 8080
    name: http2

eric-ingressgw-nssf-provisioning:
  service:
    allocateLoadBalancerNodePorts: true
  labels:      
    istiox: eric-nssf-provisioning
  enabled: true
  daemonSet: false
  ports:
  - port: 80
    targetPort: 8080
    name: http2

